language: node_js
node_js:
  - '1'
  - '2'
  - '3'
  - '4'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
script: "npm run test-travis"
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"